
name: Build, Push & Deploy 
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'use_workflow_template'

# Needed so GITHUB_TOKEN can publish to GHCR
permissions:
  contents: read
  packages: write

# env:
  # CONTAINER_REPO as secret
  # DOCKER_USERNAME as secret
  # DOCKER_PAT as secret
  
jobs:
  build-push-dockerhub:
    uses: LeidenUniversityLibrary/container-deploy-awx-action/.github/workflows/build-push-dockerhub.yml@master
    secrets: inherit
  
#  deploy-awx:
#    needs: build-push-dockerhub
#    if: github.ref_name == 'develop'
#    uses: LeidenUniversityLibrary/container-deploy-awx-action/.github/workflows/awx-deploy.yml@master
#    with:
#      image: ${{ needs.build-push-dockerhub.outputs.image }}
#      image_tag: ${{ needs.build-push-dockerhub.outputs.branch_tag }}
#    secrets: inherit
